# Generated by Django 3.1.4 on 2021-01-25 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumName', models.CharField(max_length=255)),
                ('artWork', models.ImageField(upload_to='media/images')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=255)),
                ('number_of_songs', models.IntegerField()),
                ('album_desc', models.TextField(default='Popular Album!', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistName', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media/images')),
                ('briefBio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=255)),
                ('song_length', models.IntegerField()),
                ('art_Work', models.ImageField(upload_to='media/images')),
                ('song_file', models.FileField(upload_to='media/songs')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('album_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.album')),
                ('artist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.artist')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.artist'),
        ),
    ]
