# Generated by Django 3.1.4 on 2021-01-25 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_length',
        ),
    ]
