# Generated by Django 3.1.4 on 2021-01-30 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20210125_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Browsepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('albums', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.album')),
                ('artists', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='player.artist')),
                ('songs', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='player.song')),
            ],
        ),
    ]
